-- Run this in Supabase SQL Editor.
-- This creates the private message table and Row Level Security.
-- IMPORTANT: After creating the two user accounts, replace the two UUID
-- placeholders below with their actual auth.users IDs.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz null
);

alter table public.messages enable row level security;

-- Remove old policies if you rerun this script.
drop policy if exists "two users can read messages" on public.messages;
drop policy if exists "two users can send messages" on public.messages;
drop policy if exists "two users can mark read" on public.messages;

-- Replace these with the two actual auth user UUIDs.
-- Example:
--   '11111111-1111-1111-1111-111111111111'
--   '22222222-2222-2222-2222-222222222222'

create policy "two users can read messages"
on public.messages for select
to authenticated
using (
  auth.uid() in (
    'ef5d956c-c062-4320-a60e-4a1e00045f60',
    'be47b587-1ca6-4ae6-86cf-5a04619ae69e'
  )
);

create policy "two users can send messages"
on public.messages for insert
to authenticated
with check (
  auth.uid() in (
    'ef5d956c-c062-4320-a60e-4a1e00045f60',
    'be47b587-1ca6-4ae6-86cf-5a04619ae69e'
  )
  and user_id = auth.uid()
);

create policy "two users can mark read"
on public.messages for update
to authenticated
using (
  auth.uid() in (
    'ef5d956c-c062-4320-a60e-4a1e00045f60',
    'be47b587-1ca6-4ae6-86cf-5a04619ae69e'
  )
)
with check (
  auth.uid() in (
    'ef5d956c-c062-4320-a60e-4a1e00045f60',
    'be47b587-1ca6-4ae6-86cf-5a04619ae69e'
  )
);

-- Enable realtime for new messages.
alter publication supabase_realtime add table public.messages;

-- OPTIONAL cleanup rule:
-- Do NOT automatically delete unread messages.
-- If you later want "delete only after both users have read it",
-- implement that with a server-side scheduled job/function rather
-- than trusting browser JavaScript.
